name: Read Index HTML

# Trigger the workflow on pushes to main
on:
  push:
    branches:
      - main

jobs:
  read-file:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Read and print index.html content
      - name: Read index.html
        run: cat index.html
